

GET https://hxjsbd5dk8.execute-api.eu-west-1.amazonaws.com/prod/spaces
###

POST https://hxjsbd5dk8.execute-api.eu-west-1.amazonaws.com/prod/spaces
Content-Type: application/json

{
    "location": "Paris"
}
###

GET https://hxjsbd5dk8.execute-api.eu-west-1.amazonaws.com/prod/spaces?id?id=12345
###

DELETE https://hxjsbd5dk8.execute-api.eu-west-1.amazonaws.com/prod/spaces?id?id=12345
###

PUT https://hxjsbd5dk8.execute-api.eu-west-1.amazonaws.com/prod/spaces?id=12345
Content-Type: application/json

{
    "location": "Paris2"
}
###